# Generated by Django 5.1.3 on 2024-11-09 20:02

import certificate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='document',
            field=models.FileField(upload_to=certificate.models.certificate_upload_to),
        ),
    ]
