# Generated by Django 5.1.3 on 2024-11-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_alter_certificate_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
