# Generated by Django 5.1.3 on 2024-11-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_certificate_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
