# Generated by Django 5.1.3 on 2024-11-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0004_alter_certificate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
