# Generated by Django 5.1.3 on 2024-11-21 08:38

import certificate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0005_alter_certificate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='document',
            field=models.FileField(max_length=255, upload_to=certificate.models.certificate_upload_to),
        ),
    ]
