# Generated by Django 5.1.3 on 2024-11-21 08:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0006_alter_certificate_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
