# Generated by Django 5.1.3 on 2024-12-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0008_alter_certificate_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-created_at']},
        ),
    ]
