"""
Django settings for certificatesaqa project.

Generated by 'django-admin startproject' using Django 4.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os

from pathlib import Path 
import dj_database_url
import pymysql
pymysql.install_as_MySQLdb()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent 


CSRF_TRUSTED_ORIGINS = ['https://hosting-add-production.up.railway.app/']
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5d@frk6gfo4zpxzn&q*ml#tvh0p=cho5*b0nkf(a$c9*z+0uhr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'certificatesaqa.org.za', 'www.certificatesaqa.org.za','hosting-add-production.up.railway.app' ,]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'certificate',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'certificatesaqa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'certificatesaqa.wsgi.application'
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
  'default': {
    'ENGINE': 'django.db.backends.mysql',
    'NAME': 'certificate_db',
    'USER': 'root',
    'HOST': 'switchback.proxy.rlwy.net',
    'PASSWORD': 'woGXDTIUuoeNSWlCkzOuwIcTRimtSdkG',
    'PORT': '52642', 
  }
}
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_HSTS_SECONDS = 31536000  
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

LOGIN_REDIRECT_URL = '/upload/'
LOGIN_URL = 'login'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')
STATICFILES_DIRS=(os.path.join(BASE_DIR,'static'),) 
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField' 
DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
GS_BUCKET_NAME = 'certificate_bucket'
GS_PROJECT_ID = 'certificate-442017'

# Set the media URL for accessing files
MEDIA_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/'

import base64

encoded_key = os.getenv('GOOGLE_CREDENTIALS') 
if DEBUG:
    encoded_key = 'ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiY2VydGlmaWNhdGUtNDQyMDE3IiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiYTVhNDI0NmYyZWNhNmJkOGU2OGYwODFjMWZhYTVhY2ZkYzIxYmM0MCIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZRSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2N3Z2dTakFnRUFBb0lCQVFESG4yaCsyRzFucHU4dlxuWjErU09UWGpWUkhzUkdLSEdIVWMvMTNTMm5LdDNpY1d1ZjBnVFBROUdtWlNqbjR3ci8zc2dIN1ZaZ29PalUzUFxuaDFDUEZRdjZORjNzc0pHMnVIclJaQ2hsQVBwcnhONEN6bTVqRDVqbHJ6ZjdWZGY4WXdDL256SS9ScUF0cHpadFxucC93Nld2aXU5a3lKTjU4Y3FLV2YzNG9KTW82eFVqSyttaVY3R1BnUmwyQ1B2RHhYb1pVdXRyN0hLOEYycGlJSFxuY2J2eGc1elVBa2VldWt1cmphWWx5aDVDaEpHSmdRNmFDL2dmWDFwZ0dlWU5UQ3RBVEEvcTJoWExESmN0cGw4NVxuMzVjQStzcXBYQnYzNGJKUXU1bnliblVtNXhMdFdHMXRnL1A4OGJaOFNtbU91ejFkMTQ3L1lySjZlcnZCQjQ5U1xuUlc1THZRZDNBZ01CQUFFQ2dnRUFCb1dhN0k0QW9RMTZBZzFPdU9CeW9NU1k2eVJlMHdyRnIyd0R4NDJkM1RnRlxuV2VvN1dXWDZQWHduMGY4Q3pob1VqSTRKZ1hVREtNVGl3UldBTGNuaWFYWElNeUZLV1hNVWh0UE91QXk4b2NSb1xuVVNUU2JzZkYxemM1ZDlZdS9NN0tsRTEzWHZiZFBvWHQzWGoxWU5OZVl1K213aWhBT1dKUEt2YUFOREJqMWhUZlxudzR6Q2hFUVVKRmdqWVh2OVl5ZjN6ZWxGMktWdXhZSWlhMU8wdEdrclB5QWUxNjdYaXE0Sm9zczJTTUlxNzFBSFxuZmZHTGpqZFNtTXcwL3pYMmhPY2xkdWxLWEVGY2s0YVZzREwzTUxMOXJwM3VvL3gya1E2TlJ1azJLaC9iekhhL1xucHYwdElNUU9VemVBbUtVTmZqeUNWYnlyUmhpZnBCdFV2WGh2UUROSnVRS0JnUUQxZFdodlJnc0VDTUwxdUlpbVxuczU5OUhVclh2MWgvWjc1TjNhbVZSMVc5TUNHY1ZvSzlMbDNtRDJWbytGWVJHY3czdUVTa1pBcUxDeGNiaVlFb1xuUndoY3dwcUx1djJOTGhzQTRBOHlCRGs1QU9IWmJTajBvdTFBVnFVR2hvbUxJZXZ6YTJkUVhJM2JyYUdyRUEyZVxuZHhWWFliSjViQVZUYVhJdytpOUo5R3JibndLQmdRRFFNaE9EdjlwNUxNT2h5TUFHTmJYbUJydENtcUg0Q1g4cFxuYWpDNUp5S3lIS3VITGFIclNTRE9ySlNGOG5nd0hSZ1VGSnVISyttYklScmpJbUFpN3JRUUt6VHMrVnNBRm8rQlxuOTB3ZERUdmZ4MEE0M2dEZXA4czl5NDJGNXBDWG1SQWZMRnQ1Y3NhRmdmcytYaDZ3WWUwWFhXZG9zSk5lZlp0eFxuMFFCbEw5SkZLUUtCZ0dnclZJL3N0TjRZYmN6a2JMSDZoeFFNNjJkV1lGTnBqcnp5OW5aUTJOVTZhUGsxU2JUSlxueWJYS0VPcVVnY291SFpvRURMV0xjMklBNmVTWTNZUmZhUEFjOG9PY2J1Q01rWTgwaDU1ZFpuK0huVkd0M3ZTN1xuZEY2YXB0eDNHa1krdGlrUENzQnpGdzBFeWhpVDdvT3kzQTdDZW9ESFZCZExKOWdiUlJob3J6VFhBb0dCQUx4bFxuRkJPY2dHNDJlN0Rpb0NEK2FXT0ZvOTVaWDBlOEVEM0J3ZVZKN0xPUURnZDgyNUMxMCtJeGVSVGNuTFd0SGlUTlxub1E5b1JUUURlUGtnR2k2Q0lwNmUrbjJXQnlyRlA0Y3o2TVJCUFhUNk1MdEU2VFNTVWUvUlNuZG9kRjg2T3NSNlxudHl2bkdJMm5XVnJPZ0tiTGRtZzJOV1Vlbzd4Vm5Wd1k3R3FrSTNwQkFvR0FGS1FsMkIraFk1UTFKZTE5N0o3L1xuYkFoVGRLLzdrZ1dWbnNOeUszOU9EQ0VOUnRqOEkzeVY5cnliaWp5WHlVNjNmN1NCNmdxdzNLM0cyZnVtV29lM1xuWm5SMVRsakFXN0FOMHorTG1QM3RzYUg4Y0h6cTR5RmtTcWViUFhtR1FhZVlGUVVzTkR3V045Y1Y3alRFYVV4aVxuak1pdWk4a21sb0dMb1h0Tzc2QklScEk9XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAiZGphbmdvLXN0b3JhZ2VAY2VydGlmaWNhdGUtNDQyMDE3LmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjExMDY3NDAzNDM3MDAzNDUzNzQ5MiIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvZGphbmdvLXN0b3JhZ2UlNDBjZXJ0aWZpY2F0ZS00NDIwMTcuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0K'
if not encoded_key:
    raise ValueError("GOOGLE_CREDENTIALS environment variable not set")

key_json = base64.b64decode(encoded_key).decode('utf-8')
 
service_account_path = 'service_account.json'
with open(service_account_path, 'w') as f:
    f.write(key_json)
 
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = service_account_path

# mysql://root:woGXDTIUuoeNSWlCkzOuwIcTRimtSdkG@switchback.proxy.rlwy.net:52642/railway
# woGXDTIUuoeNSWlCkzOuwIcTRimtSdkG